config/routes.rb
Rails.application.routes.draw do
  resources :filers, only: [:index, :show, :new, :create, :destroy]
  root 'filers#index'

end

app/models/filer.rb
class Filer < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
  validates :attachment, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include FilersHelper
end

app/controllers/filers_controller.rb
class FilersController < ApplicationController
  before_action :set_filer, only: [:show, :destroy]

  def index
    @filers = Filer.all
  end

  def new
    @filer = Filer.new
  end
  
  def show
    @stackedWordTree = retrieve_stacked_word_trees()
  end

  def create
    @filer = Filer.new(filer_params)

    if @filer.save
      redirect_to filers_path, notice: "The file #{@filer.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @filer.destroy
    redirect_to filers_path, notice:  "The file #{@filer.name} has been deleted."
  end

  private

  def filer_params
    params.require(:filer).permit(:name, :attachment)
  end

  def set_filer
    @filer = Filer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filers_helper.rb
module FilersHelper
  # Algorithme builder the Stacked Word Trees
  def retrieve_stacked_word_trees
    @contents = reader()
    @contents.sort! {|item1,item2| item1.length<=>item2.length}
    array_word_sort_by_length = build_dictionary(@contents)

    stacked_word_trees = []
    stacked_word_trees << array_word_sort_by_length[0][0]    
    
    index_i = 0
    while (index_i+1) < array_word_sort_by_length.length
      index_j = 0
      while index_j < array_word_sort_by_length[index_i].length    
        checker = compar_letter_by_letter(array_word_sort_by_length[0][0], array_word_sort_by_length[index_i][index_j])
        
        if checker == true
          stacked_word_trees << array_word_sort_by_length[index_i][index_j]
        end
        
        index_j += 1
      end
      index_i += 1
    end
    
    return stacked_word_trees
  end

  private
  
  def reader
    file = File.open(@filer.attachment.file.file, "r") unless @filer.blank?
    str_array = []
    while !file.blank? && !file.eof? 
      str_array << file.readline
    end
    str_array
  end

  def build_dictionary(contents)
    array_word_sort_by_length = []
    count = 3
    while count<contents.length do
      index=contents.index{|item| item.length==count}
      next_index=contents.index{|item| item.length==(count+1)}

      if !index.nil? && !next_index.nil?
        array_word_sort_by_length[count] = contents[index..(next_index-1)]
      end
      count +=1
    end
    
    if array_word_sort_by_length[3].empty? 
      return nil 
    end

    array_word_sort_by_length[3..array_word_sort_by_length.count]
  end
  
  # Required: string1.length +1 == string2.length
  def compar_letter_by_letter(string1, string2)
    checker = []
    
    string1.each_byte { 
      checker << false  
    }
   
    index_j = 0
    while index_j < string2.length
      index_i = 0
      while index_i < string1.length
        if string1[index_i].eql?(string2[index_j]) == true
          checker.insert(index_i, true)
          break
        end

        index_i += 1            
      end

      index_j += 1
    end
    
    checker = checker.take(string1.length)
    checker.each { |checke| 
      if checke == false
        return false
      end
    }
    return true
  end
end

app/views/filers/create.html.erb
<h1>Filers#create</h1>
<p>Find me in app/views/filers/create.html.erb</p>

app/views/filers/destroy.html.erb
<h1>Filers#destroy</h1>
<p>Find me in app/views/filers/destroy.html.erb</p>

app/views/filers/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New File", new_filer_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th colspan="2" >Action</th>   
    </tr>
  </thead>
  <tbody>
    <% @filers.each do |filer| %>
      <tr>
        <td><%= filer.name %></td>
        <td><%= link_to "Download File", filer.attachment_url %></td>
        <td><%= button_to "Show",  filer, method: :get, class: "btn btn-danger", confirm: "Are you sure that you wish to show the Stacked Word Trees! of #{filer.name}?" %></td>        
        <td><%= button_to "Delete",  filer, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{filer.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

app/views/filers/new.html.erb
<% if !@filer.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @filer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @filer, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/filers/show.html.erb
<h1>Stacked Word Trees</h1>

<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Stacked Word Trees for :id <%= "#{params[:id]}" %></th>
    </tr>
  </thead>
  <tbody>
  <% if !@stackedWordTree.nil? %>   
    <% @stackedWordTree.each do |content| %>
      <tr>
        <td><%= content %></td>
      </tr>
    <% end %>
  <% else %> 
      <tr>
        <td>Stacked Word Trees is empty...</td>
      </tr>      
   <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" style="padding-top:20px;">
<%= yield %>
</div>
</body>
</html>